/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_main_window (void);
GtkWidget* create_about_dialog (void);
GtkWidget* create_open_file_chooser (void);
GtkWidget* create_save_file_chooser (void);
GtkWidget* create_pu_mnu_liste (void);
GtkWidget* create_pu_msg_box (void);
GtkWidget* create_pu_input_box (void);
GtkWidget* create_ext_link_window (void);
GtkWidget* create_edit_window (void);
GtkWidget* create_index_window (void);
GtkWidget* create_file_info_box (void);
GtkWidget* create_list_window (void);
GtkWidget* create_option_window (void);
GtkWidget* create_fontselectiondialog1 (void);
GtkWidget* create_search_dialog (void);
GtkWidget* create_replace_dialog (void);
GtkWidget* create_pu_mnu_swort (void);
