/* ********************************************************
 * ZMzettelkasten2 main.c file
 * (c) 2007-2009 B.Holzhauer
 * 
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 * ****************************************************** */

/*  This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>
#include <string.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"
#include "globals.h"
#include "my_zettel.h"
#include "my_text.h"
#include "my_file.h"
//#include "functions.h"

int main (int argc, char *argv[])
{
	gnome_program_init (PACKAGE, VERSION, LIBGNOMEUI_MODULE,
                      argc, argv,
                      GNOME_PARAM_APP_DATADIR, PACKAGE_DATA_DIR,
                      NULL);

	// --- Version and CopyRight String for about_dialog ---
	char version[]="Version 0.42RC1d";
	sprintf(g_version, "ZauberMaus Zettelkasten\n(ZMzettelkasten)\n\n%s\n\n2006-2009 Bernd Holzhauer", version);

	GtkWidget *statusbar, *text, *label;
	GtkWidget *image2, *link_liste;
	GtkTextBuffer *buffer;
	FILE *fp;
	int i, fn, ret; 
	char filename[255];
	strcpy(filename, "");
	char filenameh[255];
	char c_auto[20];
	char search[20], head[40];
//	int offset_x=0;
//	int offset_y=0;


	/* --- preset globals defined in globals.h --- */
	g_maxdata=10000000;
	g_maxzeile=60000;
	g_offset_x=0;
	g_offset_y=0;
	edit_window = NULL;
	index_window = NULL;
	option_window = NULL;
	list_window = NULL;
	text_changed = FALSE;
  	current_filename = NULL;
	file_changed = FALSE;
	neuer_zettel = FALSE;
	show_autor = FALSE;
	show_stich = TRUE;
	show_text = FALSE;
	show_titel = FALSE;
	show_note = FALSE;
	show_last = FALSE;
	g_ov_active=FALSE;
	g_list_hidden = FALSE;
	g_list_todo = FALSE;
	g_list_keyed = FALSE;
	g_edit_backlink = FALSE;
	g_edit_template = FALSE;
	readonly_c = FALSE;
	readonly = FALSE;
	offset=FALSE;
	store_ext_val = FALSE;
	store_temp_val = FALSE;
	search_dialoge = NULL;
	strcpy(g_password, "");
	fn = 0;
	
	gboolean show_liste=FALSE;
	gboolean show_liste_i=FALSE;
	
	get_datum(g_datum_c); // setze heute nach g_datum
    /* process cmd line args */
    for (i=1; i<argc; i++) {
        //printf("argc:%i = %s\n", i, argv[i]);
        if (strcmp(argv[i], "-h") == 0) {
        	g_print("ZMzettelkasten %s\n [option] [filename]", version);
        	g_print("    valid Options:\n");
        	g_print("      -? - print this help\n");
        	g_print("      -l - show last edited Slip\n");
        	g_print("      -o - use the defined offset\n");
        	g_print("      -r - open in read-only mode\n");
        	g_print("      -z n - go direct to Slip n\n");
        	g_print("      -L n n n - open Index window with List of Entries\n");
        	g_print("      -S keyword - open Index with filter for keyword\n");
        	return;
        }
        if (strcmp(argv[i], "-r") == 0) {
        	printf("readonly mode\n");
        	readonly_c = TRUE;
        	readonly = TRUE;
        	offset = TRUE;
        }
        if (strcmp(argv[i], "-l") == 0) {
        	printf("show last is on\n");
        	show_last = TRUE;
        }
        if (strcmp(argv[i], "-o") == 0) {
        	printf("offset is on\n");
        	offset = TRUE;
        }
        if (argv[i][0] != '-') {
            strcpy(filename, argv[i]);
            printf("file=%s | %c\n", filename, argv[i][0]);
            fn = 1;
        }
        if (strcmp(argv[i], "-z") == 0) { // einzelner Zettel
        	i++;
        	// --- use eindex for preset
        	eindex=atoi(argv[i]);
        	printf("goto zettel %d\n", eindex);
        }
        if (strcmp(argv[i], "-L") == 0) { // Liste
        	//i++;
        	int j=1;
        	i++;
        	while(i<argc) {
        	    indexz[j]=atoi(argv[i]);
        	    g_print("    in Liste - zettel=%d\n", indexz[j]);
    			j++;
        		i++;
    		}
    		indexz[j]=0;
			show_liste=TRUE;
			break;
        }
        if (strcmp(argv[i], "-S") == 0) { // Stichwort
			i++;
			strcpy(search, argv[i]);
			show_liste_i=TRUE;
		}
    } 

#ifdef ENABLE_NLS
	setlocale (LC_ALL, "");
//#	bindtextdomain (GETTEXT_PACKAGE, "locale");
	bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
	bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
	textdomain (GETTEXT_PACKAGE);
#endif
	gtk_set_locale ();
	gtk_init (&argc, &argv);
	
	int pid=getpid();
	g_print("    myPID=%d\n", pid);

	/* main_window is a global Widget */
//g_printf("---mark create main---\n");
	main_window = GTK_WINDOW(create_main_window ());
//g_printf("---mark after create main---\n");
	set_window_title (GTK_WIDGET(main_window));

	PangoFontDescription *font_desc;
  
	/* alles was per default angezeigt werden soll */
	// --- link to text buffer ---
	text = lookup_widget (GTK_WIDGET(main_window), "main_txt_text");
  	buffer = gtk_text_view_get_buffer (GTK_TEXT_VIEW (text));
  	// --- and init tag definations ---
  	load_tag_table(buffer);
  
	statusbar = lookup_widget (GTK_WIDGET(main_window), "main_appbar");
 	gnome_appbar_set_status (GNOME_APPBAR (statusbar), _("kein Zettelkasten geöffnet"));
   
  //g_signal_connect (buffer, "changed", G_CALLBACK (on_text_changed), NULL);
//g_printf("    before link_liste\n");
	// --- setup Verweis-Liste in main_window ---
	link_liste = lookup_widget (GTK_WIDGET(main_window), "main_link_list");
	link_view = create_view_and_model_m(link_liste);

	GtkWidget *button;
	/* diable some items */
	button = lookup_widget (GTK_WIDGET (main_window), "main_btn_save"); //save-button
	gtk_widget_set_sensitive(button, FALSE);
	button = lookup_widget (GTK_WIDGET (main_window), "main_btn_new");
	gtk_widget_set_sensitive(button, FALSE);
	button = lookup_widget (GTK_WIDGET (main_window), "main_btn_edit");
	gtk_widget_set_sensitive(button, FALSE);
	// --- read_only mode = disable some widgets ---
	if (readonly){
		button = lookup_widget (GTK_WIDGET (main_window), "main_mnu_edit1");
		GtkWidget *menu = button->parent; // points to main_menu
		gtk_widget_hide(menu);
	}
	if (offset){
		g_offset_x=150;
		g_offset_y=110;
	}	
	// --- setze Titel Label bold und links ---
	label = lookup_widget (GTK_WIDGET(main_window), "main_lbl_head");
	GtkStyle *style = gtk_widget_get_style(label);
    pango_font_description_set_weight(style->font_desc, PANGO_WEIGHT_BOLD);
    gtk_widget_modify_font(label, style->font_desc);
    //gtk_misc_set_alignment(GTK_MISC (label), 0.0, 0);
    /* --- reset Pango Weight for next Labels --- 
     *     sonst sind alle folgenden Label BOLD   */
    pango_font_description_set_weight(style->font_desc, PANGO_WEIGHT_NORMAL);

	/* Set default Font name,size */
	//static PangoFontDescription *font_desc;
	char font[30];
	ret=get_config(font, "d_font");
	if (!ret) { 
		label = lookup_widget (GTK_WIDGET(main_window), "main_txt_text");
		//strcpy(font, "courier 10"); 
		g_printf("    font=%s\n", font);

		font_desc = pango_font_description_from_string (font);
		gtk_widget_modify_font (label, font_desc);
		pango_font_description_free (font_desc);
	}
 
	/* preset values from cfg file */
	get_config(c_auto, "i_text");
	if(!strncmp("1", c_auto, 1)) show_text=TRUE;
	get_config(c_auto, "i_autor");
	if(!strncmp("1", c_auto, 1)) show_autor=TRUE;
	get_config(c_auto, "i_note");
	if(!strncmp("1", c_auto, 1)) show_note=TRUE;
	get_config(c_auto, "i_titel");
	if(!strncmp("1", c_auto, 1)) show_titel=TRUE;
	//g_printf("show_text=%d\n", show_text);
	ret = get_config(g_path, "path");
	if (ret) {
		strcpy(g_path, g_get_home_dir());
		strcat(g_path, "/");
	}
	// auf int überarbeiten 
	ret = get_config(g_back, "auto_backup");
	ret = get_config(c_auto, "auto_load");
	ret = get_config(g_conv, "auto_convert");
	ret = get_config(g_autor, "autor");
	/* no Autor in file - get System User-Name */
	if (ret) strcpy(g_autor, g_get_real_name());
	//if (!g_autor) { g_autor = g_get_real_name(); }
	g_print("*** path=%s, autor=%s\n", g_path, g_autor);
  
	/*** process FileName and open it ***/
	if (fn == 1){
//		g_printf("    filename = %s\n", filename);
		// check for absolute name
		if (strncmp(filename, "/", 1)!=0) {
			// use file in default path
			strcpy(filenameh, filename);
			sprintf(filename, "%s/%s", g_path, filenameh);
		}
	} else {
		if (!strncmp("1", c_auto, 1)) {
			get_config(filename, "last");
		}
	}
	// --- test if file exist - and open it
	g_printf("    filename before test/open = '%s'\n", filename);
	if (strlen(filename)!=0) { // && !strstr(filename, "(null)")) {
//		g_print("    will test\n");
		if(test_file_exist(filename)) {
			if (!test4lock (filename)) {
				real_open_file (filename);
			}
		} else {
			sprintf(filenameh, _("File %s nicht gefunden"), filename);
			error_msg(filenameh);
		}
	}

	/* showlast edited if selected */
	if(show_last) {
		ret=last_edited();
		if (ret!=0) {
			zindex=ret;
			show_zettel(main_window);
		}
	}

	/*** Restore Fenstergeometrie (Main Window) ***/
	GtkWidget *paned;
	int left, top, width, hight;
	int vpan, active;
	
	//gtk_widget_set_size_request(main_window, 500, 400);
	//gtk_window_set_resizable(GTK_WINDOW (main_window), TRUE);
	left = get_i_config("m_left");
	top  = get_i_config("m_top");
	width = get_i_config("m_width");
	hight = get_i_config("m_hight");

	left=left-g_offset_x;
	top=top+g_offset_y;
	if (left >= 0 && top >= 0) {
		gtk_window_move(GTK_WINDOW (main_window), left, top);
	}
	if (width <= 10) width = 600;
	if (hight <= 10) hight = 400;
	//g_printf("width=%d - hight=%d\n", width, hight);
	gtk_window_resize(GTK_WINDOW (main_window), width, hight);

	vpan = get_i_config("m_vpan1");
	if (vpan > 0) {
		paned = lookup_widget (GTK_WIDGET (main_window), "main_vpaned1");
		gtk_paned_set_position(GTK_PANED (paned), vpan);
		g_printf("Location vpan1=%d\n", vpan);
	}
	vpan = get_i_config("m_hpan1");
	if (vpan > 0) {
		paned = lookup_widget (GTK_WIDGET (main_window), "main_hpaned1");
		gtk_paned_set_position(GTK_PANED (paned), vpan);
		g_printf("Location hpan1=%d\n", vpan);
	}
	vpan = get_i_config("m_vpan2");
	if (vpan > 0) {
		paned = lookup_widget (GTK_WIDGET (main_window), "main_vpaned2");
		gtk_paned_set_position(GTK_PANED (paned), vpan);
		g_printf("Location vpan2=%d\n", vpan);
	}
	int val = get_i_config("toolbar");
	if (val==1) {
		paned = lookup_widget (GTK_WIDGET (main_window), "main_toolbar");
		gtk_toolbar_set_style (GTK_TOOLBAR (paned), GTK_TOOLBAR_ICONS);
	}
	if (val==2) {
		paned = lookup_widget (GTK_WIDGET (main_window), "main_toolbar");
		gtk_toolbar_set_style (GTK_TOOLBAR (paned), GTK_TOOLBAR_TEXT);
	}
	
	//g_printf("path=%s auto=%s back=%s file=%s\n", g_path, c_auto, g_back, filename);
	/* restore = activate Toggle Buttons */
	active = get_i_config("m_sview");
	g_print("    active=%d\n", active);
	if (active > 0) {
		button = lookup_widget (GTK_WIDGET(main_window), "main_cbtn_stichview");
		gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(button), TRUE);
	}
	active = get_i_config("m_iactive");
	if (active > 0) {
		button = lookup_widget(GTK_WIDGET(main_window), "main_cbtn_inactive");
		gtk_toggle_button_set_active(GTK_TOGGLE_BUTTON(button), TRUE);
	}
	gtk_widget_show (GTK_WIDGET(main_window));
	
	/* enable PDF Button if LaTeX files found */
	g_print("    Test for pdflatex\n");
	button = lookup_widget(GTK_WIDGET(main_window), "main_btn_pdf");
	if(!test_file_exist("/usr/bin/pdflatex")) {
		g_print("*** Program 'pdflatex' is not available\n");
		gtk_widget_set_sensitive(button, FALSE);
	}
	if(!test_file_exist("/usr/local/share/applications/ZMzettelkasten/export.hdr")) {
		g_print("*** File '/usr/local/share/applications/ZMzettelkasten/export.hdr' is not installed\n");
		gtk_widget_set_sensitive(button, FALSE);
	}
//g_print("+++MARK2+++\n");
	if(show_liste) show_index_titel("from CMD Line");
	if(show_liste_i) {
		ret=fill_indexz_stich(search);
		g_printf("    ready %d catchwords - line: %s\n", ret, search);
		sprintf(head, _("1. Stichwort = %s"),  search);
		g_ov_active=TRUE;
		show_index_titel(head);
	}

	/* loop here til end */	
	gtk_main ();
	return 0;
}
